# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f0c1c2d43c40b2ce4b13338f0f180b25be43e657801270fec82f80c953ae12309d2b4ffca04e6edf313e66e64a4ce6700a9b9a1468fc96513a2568f9f87fb6

test:
  secret_key_base: 6b8594d6c6404e9d979454214b487a907e1339fa796844cbcb98ad4664e844651725f7932cd7610cad06657ef462070c9965f1a4695728272b65c49c86035e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
